# Generated by Django 4.1 on 2022-08-06 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_catalog_parent_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='parent_catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='catalog.catalog'),
        ),
    ]
