# Generated by Django 4.1 on 2022-08-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_promo_alter_product_price_product_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='name',
            field=models.CharField(default='sale', max_length=20),
            preserve_default=False,
        ),
    ]
