# Generated by Django 4.1 on 2022-08-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_catalog',
            new_name='parent_category',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
