# Generated by Django 4.1 on 2022-08-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('a', 'creating'), ('b', 'confirmed'), ('c', 'waiting for payment'), ('d', 'preparing'), ('f', 'closed')], default='a', max_length=1),
            preserve_default=False,
        ),
    ]
