# Generated by Django 4.1 on 2022-08-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('a', 'creating'), ('b', 'confirmed'), ('c', 'waiting for payment'), ('d', 'preparing'), ('f', 'closed')], default='a', max_length=1),
        ),
    ]
